name: Go pipeline
on: 
  push: 
     branches: [ "main" ]
  pull_request: 
     branches: [ "main" ]
     
jobs: 
    Build:
        runs-on: ubuntu-latest
        steps: 
          - name: checkout repository code 
            uses: actions/checkout@v2
            
          - name: setup Go
            uses: actions/setup-go@v2
            with:
                  go-version: 1.19
          - name: go build
            run: go build -v ./...
          
    
    
    Build-and-push-image:
      runs-on: ubuntu-latest
      needs: Build
      if: success() && github.ref == 'refs/heads/main'
     
      steps:
       - name: checkout code
         uses: actions/checkout@v2
         
       - name: set up QEMU
         uses: docker/setup-qemu-action@v2
       
       
       - name: set up docker buildx
         uses: docker/setup-buildx-action@v2 
         with:
           version: v0.7.0
         
       
       - name: Login to DockerHub
         uses: docker/login-action@v2
         with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
        
       - name: Build and push
         uses: docker/build-push-action@v3
         with:
           context: .
           push: true
           tags: teamrulerhng9/backend:latest

      
      
    Deploy-staging:
           runs-on: ubuntu-latest
           needs: Build-and-push-image
           if: success() && github.ref == 'refs/heads/main' 
           steps:

             - name: deploy to staging server
               uses: appleboy/ssh-action@master
               with: 
                 host: ${{ secrets.HOST }}
                 username: ${{ secrets.USERNAME }}
                 password: ${{ secrets.Password }}
                 port: ${{ secrets.PORT }}
                 script: |
                     sudo docker-compose pull
                     sudo docker-compose up -d
                  
<<<<<<< HEAD

=======
>>>>>>> 7e323ec4e8fe1d75789484806e3b6ff9427d3bd7
    Deploy-prod: 
             runs-on: ubuntu-latest
             needs: ["Build", "Deploy-staging"]
             if: success() && github.ref == 'refs/heads/main' 
             steps:

                - name: deploy to staging server
                  uses: appleboy/ssh-action@master
                  with: 
                    host: ${{ secrets.PROD_HOST }}
                    username: ${{ secrets.USERNAME }}
                    password: ${{ secrets.Password }}
                    port: ${{ secrets.PORT }}
                    script: |
                       cd todo-docker
                       sudo docker-compose pull
                       sudo docker-compose up -d
